### ISSUE TITLE
Push notification token fails to send to database

### ISSUE THREAD

**Issue by brandon-PG** [pg-irc/pathways-frontend#1737]
```
Network request failed
at node_modules/whatwg-fetch/dist/fetch.umd.js:535:17 in setTimeout$argument_0

The above error occurred in task requestPushNotificationToken
    created by takeLatest(PUSH_NOTIFICATION_TOKEN_REQUEST, requestPushNotificationToken)
    created by watchRequestPushNotificationToken
Tasks cancelled due to error:
takeLatest(PUSH_NOTIFICATION_TOKEN_REQUEST, requestPushNotificationToken)
at node_modules/@sentry/utils/dist/instrument.js:110:42 in <anonymous>
at node_modules/@redux-saga/core/dist/io-1d6eccda.js:115:2 in logError
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1006:13 in end
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:816:4 in abort
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:831:10 in task.cont
at http://192.168.1.71:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:317296:15 in end
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:816:4 in abort
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:831:10 in task.cont
at http://192.168.1.71:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:317296:15 in end
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:816:4 in abort
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:831:10 in task.cont
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1181:15 in next
at http://192.168.1.71:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:317460:10 in currCb
at node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:399:2 in resolvePromise
```

### Acceptance Criteria 
- [ ]  Push notification is viewable in the heroku db when a user opens the app

**Comment by Farouk-PG** [comment]
This is fixed. Closing!
